conference_abbrev = {
    'Advances in Neural Information Processing Systems': 'NeurIPS', 
    'NIPS': 'NIPS', # alias
    'International Conference on Machine Learning': 'ICML', 
    'International Conference on Learning Representations': 'ICLR', 
    'International Conference on Computer Vision': 'ICCV', 
    'European Conference on Computer Vision': 'ECCV', 
    'International Joint Conference on Artificial Intelligence': 'IJCAI', 
    'Association for the Advancement of Artificial Intelligence': 'AAAI', 
    'International Conference on Robotics and Automation': 'ICRA', 
    'Robotics: Science and Systems': 'RSS', 
    'International Conference on Intelligent Robots and Systems': 'IROS', 
    'Conference on Computer Vision and Pattern Recognition': 'CVPR',
    'IEEE International Conference on Computer Vision': 'ICCV', 
    'IEEE Conference on Computer Vision and Pattern Recognition': 'CVPR',
    'European Signal Processing Conference (EUSIPCO)': 'EUSIPCO',
    'IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)': 'ICASSP',
    'IEEE International Conference on Multimedia and Expo (ICME)': 'ICME',
    'IEEE International Conference on Image Processing (ICIP)': 'ICIP',
    'Findings of the Association for Computational Linguistics': 'ACL',
    'Conference on Empirical Methods in Natural Language Processing': 'EMNLP',
    'Asian Conference on Machine Learning': 'ACML',
    'International Conference on Data Mining': 'ICDM',
    'Pattern Recognition and Computer Vision': 'PRCV',
    'International Conference on Multimedia and Expo': 'ICME',
    'International Conference on Computer Vision Theory and Applications': 'VISAPP',
    'International Conference on Computer Vision and Graphics': 'ICCVG',
    'International Conference on Computer Vision and Image Processing': 'ICCVIP',
}    